apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTc=  # base64 of mongodb://mongodb:27017
  REDIS_URL: cmVkaXM6Ly9yZWRpczozNzkvMA==  # base64 of redis://redis:6379/0
  APP_ENV: cHJvZA==  # base64 of prod